<?php

namespace AppBundle\Repository;

/**
 * cr13_andreas_harasztosi_bigeventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cr13_andreas_harasztosi_bigeventsRepository extends \Doctrine\ORM\EntityRepository
{
}
